<div id="adminProfileModal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-black/45 p-4" onclick="if(event.target===this) closeAdminProfileModal()">
    <section class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="adminProfileTitle">
        <div class="flex items-center justify-between border-b border-[#E5D8CC] bg-[#FFFCF9] px-5 py-4 sm:px-6"><div><h2 id="adminProfileTitle" class="font-['Poppins'] text-lg font-bold">Edit Profil Admin</h2><p class="mt-1 text-xs text-[#7A6A60]">Ubah nama dan password akun yang sedang login.</p></div><button type="button" onclick="closeAdminProfileModal()" class="rounded-lg px-3 py-2 text-xl text-[#7A6A60] hover:bg-[#F5EFE8]" aria-label="Tutup">×</button></div>
        <form method="POST" action="{{ route('admin.profil.update') }}" class="flex flex-col gap-4 p-5 sm:p-6">@csrf
            <label class="flex flex-col gap-2"><span class="text-sm font-semibold">Nama Admin</span><input name="name" value="{{ old('name', auth()->user()->name) }}" maxlength="255" required class="h-11 rounded-lg border border-[#D8C9BC] px-3.5 text-sm outline-none focus:border-[#5C4033]">@error('name')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-2"><span class="text-sm font-semibold">Password Lama</span><span class="relative"><input id="profileOldPassword" type="password" name="old_password" required autocomplete="current-password" class="h-11 w-full rounded-lg border border-[#D8C9BC] px-3.5 pr-12 text-sm outline-none focus:border-[#5C4033]"><button type="button" onclick="toggleAdminPassword('profileOldPassword',this)" class="absolute inset-y-0 right-0 flex w-11 items-center justify-center text-[#7A6A60]" aria-label="Lihat password"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button></span>@error('old_password')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-2"><span class="text-sm font-semibold">Password Baru</span><span class="relative"><input id="profileNewPassword" type="password" name="new_password" required minlength="8" autocomplete="new-password" class="h-11 w-full rounded-lg border border-[#D8C9BC] px-3.5 pr-12 text-sm outline-none focus:border-[#5C4033]"><button type="button" onclick="toggleAdminPassword('profileNewPassword',this)" class="absolute inset-y-0 right-0 flex w-11 items-center justify-center text-[#7A6A60]" aria-label="Lihat password"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button></span>@error('new_password')<span class="text-xs text-red-600">{{ $message }}</span>@enderror<p class="text-xs text-[#7A6A60]">Minimal 8 karakter.</p></label>
            <div class="flex justify-end gap-2 border-t border-[#E5D8CC] pt-4"><button type="button" onclick="closeAdminProfileModal()" class="rounded-lg border border-[#D8C9BC] px-4 py-2.5 text-sm font-semibold text-[#5C4033]">Batal</button><button type="submit" class="rounded-lg bg-[#5C4033] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#452F26]">Simpan</button></div>
        </form>
    </section>
</div>
<script>
function openAdminProfileModal(){const m=document.getElementById('adminProfileModal');m?.classList.remove('hidden');m?.classList.add('flex');document.body.classList.add('overflow-hidden')}
function closeAdminProfileModal(){const m=document.getElementById('adminProfileModal');m?.classList.add('hidden');m?.classList.remove('flex');document.body.classList.remove('overflow-hidden')}
function toggleAdminPassword(id,button){const input=document.getElementById(id);input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'Lihat password':'Sembunyikan password')}
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeAdminProfileModal()});
@if(session('open_profile_modal')) openAdminProfileModal(); @endif
</script>
